#!/usr/bin/env bash
#Install nginx web server

# Update package repositories
sudo apt-get update

# Install Nginx
sudo apt-get install nginx -y

# Configure Nginx to return "Hello World!" at the root URL
echo "server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;
        index index.html index.htm;

        server_name _;

        location / {
                return 200 'Hello World!';
        }
}" | sudo tee /etc/nginx/sites-available/default

# Create symbolic link to enable the site
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

# Restart Nginx
sudo nginx -s reload
