#!/usr/bin/env bash
# A script that installs nginx server on an ubuntu linux distro.
# The installed server listens to port 80 (HTTP) for connection
# And serves a default page index.html on the HTTP  GET request.

sudo apt-get update -y

sudo apt-get install nginx -y

echo "server {
	listen 80 default_server;
        listen [::]:80 default_server;

	root /var/www/html;
	index index.html index.htm;

	server_name _;

	location / {
		try_files \$uri \$uri/ =404;
	}
}" | sudo tee /etc/nginx/sites-available/default

sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

echo "Hello World!" | sudo tee /var/www/html/index.html

service nginx restart
