#!/usr/bin/env bash
#Bash script that displays the PID, along with the process name, of processes whose name contain the word bash
# shellcheck disable=SC2009

for pid in /proc/[0-9]*/cmdline; do
    if [[ -f "$pid" ]]; then
        proc_name=$(tr -d '\0' < "$pid")
        if [[ "$proc_name" == *'bash'* ]]; then
            pid_num=$(echo "$pid" | awk -F'/' '{print $(NF-1)}')
            echo "$pid_num $proc_name"
        fi
    fi
done
