#!/usr/bin/env bash
#Tell the story of passwd

while IFS=':' read -r username _ password _ uid _ gid _ info _ home _ shell _; do
    echo " The user $username is part of the $gid gang, "\
    "lives in $home and rides $shell. $uid's place "\
    "is protected by the passcode $password, more info "\
    "about the user here: $info"
done < "/etc/passwd"
