#!/usr/bin/env bash
# Display "bad luck from China" on 4, "bad luck from Japan" on 9, "bad luck from Italy" f0n 17

i=1

while [ $i -le 20 ]
do
    case $i in
        4)
            echo "$i"
	    echo "bad luck from China"
            ;;
        9)
            echo "$i"
	    echo "bad luck from Japan"
            ;;
        17)
            echo "$i"
	    echo "bad luck from Italy"
            ;;
        *)
            echo "$i"
            ;;
    esac

    ((i++))
done
