#!/usr/bin/env bash
#a Bash script that displays content of the current directory In a list format

for file in *; do
    if [ -f "$file" ] && [[ ! "$file" == .* ]]; then
        rm_part=$(echo "$file" | cut -d'-' -f2-)
        echo "$rm_part"
    fi
done
